# Generated by Django 5.2 on 2025-07-18 08:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_alter_choir_cover_image_alter_choir_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1234567890/profiles/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
