# Generated by Django 5.2 on 2025-07-18 22:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_socialpost_height_socialpost_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='media_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
