# Generated by Django 5.2 on 2025-07-24 16:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_alter_socialpost_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
